# CMake generated Testfile for 
# Source directory: /data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests
# Build directory: /data/4/users/jsowa/j-pet-framework-examples/examples/ModularDetectorAnalysis/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TimeWindowCreatorToolsTest.x "/data/4/users/jsowa/j-pet-framework-examples/examples/ModularDetectorAnalysis/tests/TimeWindowCreatorToolsTest.x" "--log_level=error" "--log_format=XML" "--log_sink=TimeWindowCreatorToolsTest.xml")
set_tests_properties(TimeWindowCreatorToolsTest.x PROPERTIES  _BACKTRACE_TRIPLES "/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;37;add_test;/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;53;package_add_test;/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;0;")
add_test(SignalFinderToolsTest.x "/data/4/users/jsowa/j-pet-framework-examples/examples/ModularDetectorAnalysis/tests/SignalFinderToolsTest.x" "--log_level=error" "--log_format=XML" "--log_sink=SignalFinderToolsTest.xml")
set_tests_properties(SignalFinderToolsTest.x PROPERTIES  _BACKTRACE_TRIPLES "/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;37;add_test;/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;53;package_add_test;/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;0;")
add_test(SignalTransformerToolsTest.x "/data/4/users/jsowa/j-pet-framework-examples/examples/ModularDetectorAnalysis/tests/SignalTransformerToolsTest.x" "--log_level=error" "--log_format=XML" "--log_sink=SignalTransformerToolsTest.xml")
set_tests_properties(SignalTransformerToolsTest.x PROPERTIES  _BACKTRACE_TRIPLES "/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;37;add_test;/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;53;package_add_test;/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;0;")
add_test(HitFinderToolsTest.x "/data/4/users/jsowa/j-pet-framework-examples/examples/ModularDetectorAnalysis/tests/HitFinderToolsTest.x" "--log_level=error" "--log_format=XML" "--log_sink=HitFinderToolsTest.xml")
set_tests_properties(HitFinderToolsTest.x PROPERTIES  _BACKTRACE_TRIPLES "/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;37;add_test;/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;53;package_add_test;/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;0;")
add_test(EventCategorizerToolsTest.x "/data/4/users/jsowa/j-pet-framework-examples/examples/ModularDetectorAnalysis/tests/EventCategorizerToolsTest.x" "--log_level=error" "--log_format=XML" "--log_sink=EventCategorizerToolsTest.xml")
set_tests_properties(EventCategorizerToolsTest.x PROPERTIES  _BACKTRACE_TRIPLES "/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;37;add_test;/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;53;package_add_test;/data/4/users/jsowa/j-pet-framework-examples/ModularDetectorAnalysis/tests/CMakeLists.txt;0;")
