# CMake generated Testfile for 
# Source directory: /data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests
# Build directory: /data/4/users/jsowa/j-pet-framework-examples/examples/LargeBarrelAnalysis/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(EventCategorizerToolsTest.x "/data/4/users/jsowa/j-pet-framework-examples/examples/LargeBarrelAnalysis/tests/EventCategorizerToolsTest.x" "--log_level=error" "--log_format=XML" "--log_sink=EventCategorizerToolsTest.xml")
set_tests_properties(EventCategorizerToolsTest.x PROPERTIES  _BACKTRACE_TRIPLES "/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;35;add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;58;package_add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;0;")
add_test(HitFinderToolsTest.x "/data/4/users/jsowa/j-pet-framework-examples/examples/LargeBarrelAnalysis/tests/HitFinderToolsTest.x" "--log_level=error" "--log_format=XML" "--log_sink=HitFinderToolsTest.xml")
set_tests_properties(HitFinderToolsTest.x PROPERTIES  _BACKTRACE_TRIPLES "/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;35;add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;54;package_add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;0;")
add_test(SignalFinderToolsTest.x "/data/4/users/jsowa/j-pet-framework-examples/examples/LargeBarrelAnalysis/tests/SignalFinderToolsTest.x" "--log_level=error" "--log_format=XML" "--log_sink=SignalFinderToolsTest.xml")
set_tests_properties(SignalFinderToolsTest.x PROPERTIES  _BACKTRACE_TRIPLES "/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;35;add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;60;package_add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;0;")
add_test(TimeWindowCreatorToolsTest.x "/data/4/users/jsowa/j-pet-framework-examples/examples/LargeBarrelAnalysis/tests/TimeWindowCreatorToolsTest.x" "--log_level=error" "--log_format=XML" "--log_sink=TimeWindowCreatorToolsTest.xml")
set_tests_properties(TimeWindowCreatorToolsTest.x PROPERTIES  _BACKTRACE_TRIPLES "/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;35;add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;51;package_add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;0;")
add_test(UniversalFileLoaderTest.x "/data/4/users/jsowa/j-pet-framework-examples/examples/LargeBarrelAnalysis/tests/UniversalFileLoaderTest.x" "--log_level=error" "--log_format=XML" "--log_sink=UniversalFileLoaderTest.xml")
set_tests_properties(UniversalFileLoaderTest.x PROPERTIES  _BACKTRACE_TRIPLES "/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;35;add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;60;package_add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;0;")
add_test(ToTEnergyConverterFactoryTest.x "/data/4/users/jsowa/j-pet-framework-examples/examples/LargeBarrelAnalysis/tests/ToTEnergyConverterFactoryTest.x" "--log_level=error" "--log_format=XML" "--log_sink=ToTEnergyConverterFactoryTest.xml")
set_tests_properties(ToTEnergyConverterFactoryTest.x PROPERTIES  _BACKTRACE_TRIPLES "/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;35;add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;56;package_add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;0;")
add_test(ToTEnergyConverterTest.x "/data/4/users/jsowa/j-pet-framework-examples/examples/LargeBarrelAnalysis/tests/ToTEnergyConverterTest.x" "--log_level=error" "--log_format=XML" "--log_sink=ToTEnergyConverterTest.xml")
set_tests_properties(ToTEnergyConverterTest.x PROPERTIES  _BACKTRACE_TRIPLES "/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;35;add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;60;package_add_test;/data/4/users/jsowa/j-pet-framework-examples/LargeBarrelAnalysis/tests/CMakeLists.txt;0;")
